var questions = 
    [
        {question: "What is the capital of France?", choices: ["Paris", "London", "Berlin", "Madrid"], correctAnswer: 0},
        {question: "What is 2 + 2?", choices: ["3", "4", "5", "6"], correctAnswer: 1},
        {question: "What is 15 * 19?", choices: [285, 284, 286, 287], correctAnswer: 0},
        {question: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Leo Tolstoy", "Mark Twain"], correctAnswer: 1},
        {question: "What is the hottest planet in our solar system?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correctAnswer: 0},
        {question: "What is 9 * 2?", choices: [15, 18, 19, 16], correctAnswer: 1},
        {question: "How many continents are there?", choices: ["5", "6", "7", "8"], correctAnswer: 2},
        {question: "Which element is said to keep bones strong?", choices: ["Calcium", "Iron", "Oxygen", "Hydrogen"], correctAnswer: 0},
        {question: "What is 8 - 19?", choices: [-12, -10, -11, -11], correctAnswer: 2},
        {question: "In what year did the Titanic sink?", choices: ["1910", "1912", "1914", "1916"], correctAnswer: 1},
        {question: "What force pulls objects towards the Earth?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correctAnswer: 1},
        {question: "What is 7 * 3?", choices: [19, 23, 21, 24], correctAnswer: 2},
        {question: "How many continents are there?", choices: ["5", "6", "7", "8"], correctAnswer: 2},
        {question: "What force pulls objects towards the Earth?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correctAnswer: 1},
        {question: "What is 9 * 11?", choices: [96, 101, 99, 100], correctAnswer: 2},
        {question: "What is the largest planet in our solar system?", choices: ["Earth", "Mars", "Jupiter", "Saturn"], correctAnswer: 2},
        {question: "What is the hottest planet in our solar system?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correctAnswer: 0},
        {question: "What is 4 * 12?", choices: [46, 51, 50, 48], correctAnswer: 3},
        {question: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Leo Tolstoy", "Mark Twain"], correctAnswer: 1},
        {question: "What force pulls objects towards the Earth?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correctAnswer: 1},
        {question: "What is 12 * 11?", choices: [129, 132, 130, 135], correctAnswer: 1},
        {question: "How many continents are there?", choices: ["5", "6", "7", "8"], correctAnswer: 2},
        {question: "What force pulls objects towards the Earth?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correctAnswer: 1},
        {question: "What is 12 * 4?", choices: [45, 47, 48, 48], correctAnswer: 2},
        {question: "What is the capital of France?", choices: ["London", "Berlin", "Paris", "Rome"], correctAnswer: 2},
        {question: "What is the chemical symbol for water?", choices: ["H2O", "CO2", "O2", "He"], correctAnswer: 0},
        {question: "What is 8 - 8?", choices: [0, 2, 0, -3], correctAnswer: 0},
        {question: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Leo Tolstoy", "Mark Twain"], correctAnswer: 1},
        {question: "What is the hottest planet in our solar system?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correctAnswer: 0},
        {question: "What is 10 * 16?", choices: [159, 163, 157, 160], correctAnswer: 3},
        {question: "What is the capital of France?", choices: ["London", "Berlin", "Paris", "Rome"], correctAnswer: 2},
        {question: "What force pulls objects towards the Earth?", choices: ["Magnetism", "Gravity", "Friction", "Tension"], correctAnswer: 1}
        // Add more questions as needed    
    ];